# Generated by Django 5.2 on 2025-08-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorTransferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_description', models.CharField(max_length=255)),
                ('student_year', models.CharField(max_length=20)),
                ('pre_requisite', models.CharField(blank=True, max_length=255, null=True)),
                ('co_requisite', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(max_length=20)),
                ('school_year_offered', models.CharField(max_length=20)),
                ('total_academic_units', models.FloatField()),
                ('final_grade', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
