# Generated by Django 5.2.6 on 2025-10-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalDocuments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listfinaltor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Unknown', 'Unknown'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Finalized', 'Finalized')], default='Pending', max_length=20),
        ),
    ]
