# Generated by Django 5.2.6 on 2025-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_cittorcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tortransferee',
            name='account_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
