# Generated by Django 5.2.6 on 2025-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_tortransferee_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareResultTOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, verbose_name='Account ID')),
                ('subject_code', models.CharField(max_length=50, verbose_name='Subject Code')),
                ('subject_description', models.CharField(max_length=255, verbose_name='Description')),
                ('total_academic_units', models.FloatField(verbose_name='Units')),
                ('final_grade', models.FloatField(verbose_name='Final Grade')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
            ],
        ),
    ]
