# Generated by Django 5.2 on 2025-09-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditProfile',
            new_name='CreditAccount',
        ),
    ]
