# Generated by Django 5.2 on 2025-09-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0002_rename_creditprofile_creditaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='AccountPass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
