# Generated by Django 5.2.6 on 2025-10-10 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=50)),
                ('applicant_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
